### ISSUE TITLE
Backrefs to Session model from User model

### ISSUE THREAD

**Issue by uktamjon-komilov** [bekhzod91/snoopy#1]
Hi!
I am really interested in your snoopy project. I came accross with this line in Session model, is that correct?

https://github.com/bekhzod91/snoopy/blob/df74649c758fd3904cd9e7e991bbf2e1792700fe/snoopy/auth/models/session.py#L14    

`user = db.relationship('User', backref=db.backref('posts', lazy=True))`

**Comment by bekhzod91** [comment]
Hi Uktamjon, Sorry for taking so long to answer you I was busy.
I appreciate your interest in this project. About your notes yeap this part of code is incorrect ```backref=db.backref('posts', lazy=True)``` I already fix this code in new release 0.2.0.

If you have any question to ahead...
