### ISSUE TITLE
Suspiciously Wrong Password Expiry DateTime

### ISSUE THREAD

**Issue by uktamjon-komilov** [bekhzod91/snoopy#2]
I think there is a bug where you set the token expiry datetime. I don't whether you have intentionally left it so.

Here is the permalink: https://github.com/bekhzod91/snoopy/blob/659a610a51e1a813f959344d49408e705e17c662/snoopy/auth/services/forgot_password.py#L44

But here: https://github.com/bekhzod91/snoopy/blob/659a610a51e1a813f959344d49408e705e17c662/snoopy/auth/services/forgot_password_confirm.py#L25

you have checked if it expired.

It seems wrong, because it expires as soon as being generated. I think you have forgot to add **timedelta** to the expiry date when generating.

Thanks!

**Comment by bekhzod91** [comment]
Yes, you're right, the expiration date should be greater than the current time, I think 2 hours is enough. If you want sent pull request to fix this bug

**Comment by bekhzod91** [comment]
@uktamjon-komilov this issue fixed in [0.2.1](https://github.com/bekhzod91/snoopy/commit/f1538b6998d69b8d12078c9fe91faf14580aadd4) version

**Comment by bekhzod91** [comment]
@uktamjon-komilov this issue fixed in [0.2.1](https://github.com/bekhzod91/snoopy/commit/f1538b6998d69b8d12078c9fe91faf14580aadd4) version
